apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
  labels:
    app: httpbin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          env:
            - name: DD_SERVICE
              value: "httpbin"  # The service name in Datadog
            - name: DD_ENV
              value: "dev"  # Set this according to your environment (e.g., dev, staging, prod)
            - name: DD_TRACE_AGENT_URL
              value: "http://datadog-agent:8126"  # Ensure this points to the Datadog agent in the same namespace
            - name: DD_APM_ENABLED
              value: "true"  # Enable APM traces for this container
            - name: DD_LOGS_ENABLED
              value: "true"  # Enable log collection (optional)
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: default
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

